apiVersion: apps/v1
kind: Deployment
metadata:
  name: rep-info
  labels:
    connection: attachinng-service
  annotations:
    adding: giving-additional-info
  namespace: dev-group
spec:
  replicas: 4
  minReadySeconds: 5
  selector:
    matchLabels:
      connection: attachinng-service
  template: 
    metadata:
      labels:
        connection: attachinng-service
      name: tem-info         
    spec: 
       containers:
         - image: sravanthi2003/mycssimages:electric
           name: image-pet
           ports:
             - containerPort: 8080
               protocol: TCP
           startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 2
           livenessProbe:
             httpGet: 
               port: 80
             initialDelaySeconds: 10
             periodSeconds: 2
             successThreshold: 1
             failureThreshold: 2      
           readinessProbe:
             exec:
               command: 
                 - sh
                 - -c 
                 - "echo:hello"
             initialDelaySeconds: 10
             periodSeconds: 2
             successThreshold: 1
             failureThreshold: 2
           resources:
             limits: 
               cpu: 200m
               memory: 400Mi
             requests:
               cpu: 200m
               memory: 400Mi